APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:bjMP2NwrjXYYi0twlciKgu6IkCNuMGdQXqJfagdTz5U=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=admin_new
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DRIVER=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.hostinger.com
MAIL_PORT=465
MAIL_USERNAME=info@jippymart.in
MAIL_PASSWORD=Zxcasdqwe@123.
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=info@jippymart.in
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

 FIREBASE_APIKEY="AIzaSyAf_lICoxPh8qKE1QnVkmQYTFJXKkYmRXU"
 FIREBASE_AUTH_DOMAIN="jippymart-27c08.firebaseapp.com"
 FIREBASE_DATABASE_URL="https://jippymart-27c08-default-rtdb.firebaseio.com"
 FIREBASE_PROJECT_ID="jippymart-"
 FIREBASE_STORAGE_BUCKET="jippymart-27c08.firebasestorage.app"
 FIREBASE_MESSAAGING_SENDER_ID="592427852800"
 FIREBASE_APP_ID="1:592427852800:web:f74df8ceb2a4b597d1a4e5"
 FIREBASE_MEASUREMENT_ID="G-ZYBQYPZWCF"

 FIRESTORE_PROJECT_ID=jippymart-27c08
 FIREBASE_CREDENTIALS=storage/app/firebase/credentials.json

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
